

TRANSIT_GATEAWAY_NODE_SIZE = 60
VPC_NODE_SIZE = 20
VPN_NODE_SIZE = 10
DIRECT_CONNECT_NODE_SIZE = 50

VPC_PEER_WIDTH = 2
TRANSIT_GATEWAY_PEER_WIDTH = 6
TGW_VPC_ATTCH_WIDTH = 1
TGW_VPN_ATTACH_WIDTH = 1
TGW_DIRECT_CONNECT_WIDTH=4
VPC_VPN_EDGE_WIDTH = 1
DIRECT_CONNECT_VPN_CONNECTION_WIDTH=2
DIRECT_CONNECT_CONNECTION_GATEWAY_WIDTH=4